### ISSUE TITLE
Need help to understand shadowsocks-go configuration

### ISSUE THREAD

**Issue by myocytebd** [database64128/shadowsocks-go#33]
About "server instance" (not server property):  
1. How to bound "server instance" to a specific IP?  
    I tried to set ```servers.listen: "127.0.0.1:<port>",``` but it is not bound to IP.  
    ```curl -x "socks5://<self-public-IP>:<port>" -ipv4 -k -v -o gl.htm www.google.com``` is able to fetch the webpage.  
2. How to bound "server instance" to multiple IP:port?  

For "dns"+"router" properties:  
1. When a route has no "toXXX" properties or all "toXXX" properties are empty, does it hit all or hit none?  
2. What if routes have conflictions - when multiple rules may hit same dst, does it take 1st route, or random route?  
3. What if a route partially hit or not hit?
    e.g. docs/client.json: router.routes.name: "cn-verify-ip"
    If "toDomainSets" hits but "toMatchedDomainExpectedGeoIPCountries" misses, does it fallback to next route, or "defaultTCPClientName"?  

Thanks for your help.

**Comment by database64128** [comment]
Thank you for asking. These are very good questions.

> but it is not bound to IP.

Please post the full configuration and use `ss -tuln` to check the bound address.

> How to bound "server instance" to multiple IP:port?

You cannot bind a single server to multiple addresses, because in shadowsocks-go's current architecture, each server only opens a single socket, which can only bind to one address.

You can configure multiple servers with different listen addresses. If your goal is to prevent access from certain networks, I would recommend sticking to a single server with unspecified listen address and using firewall rules to restrict access.

> When a route has no "toXXX" properties or all "toXXX" properties are empty, does it hit all or hit none?

When there are no destination criteria (`toXXX`) in the route, a request's destination simply won't affect the outcome. Check out the in-code documentation: https://pkg.go.dev/github.com/database64128/shadowsocks-go/router#RouteConfig

> What if routes have conflictions - when multiple rules may hit same dst, does it take 1st route, or random route?

Routes are matched in order. The router only takes the first match.

> e.g. docs/client.json: router.routes.name: "cn-verify-ip"
If "toDomainSets" hits but "toMatchedDomainExpectedGeoIPCountries" misses, does it fallback to next route, or "defaultTCPClientName"?

The router will go on to look at the next route. The default route is only taken when all other routes fail to match.
